spring:
  batch:
    job:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create
    show-sql: false

mongock:
  runner-type: InitializingBean
  change-logs-scan-package:
    - ru.otus.migration.changelog

#debug: true
